version: '3'
volumes:
  kaspad_data: {}
services:
  kaspad:
    hostname: kaspad
    restart: always
    build:
      context: .
      dockerfile: kaspad/Dockerfile
    volumes:
      - kaspad_data:/home/kaspa/.rusty-kaspa
    environment:
      - 'RUST_BACKTRACE=1'
